schema_version = 1

[package]
name = "m4"
version = "1.4.19"
release = 1
epoch = 0
description = "Traditional Unix macro processor"
license = "GPL-3.0-or-later"
channel = "system"
arch = "amd64"

dependencies = [
    "virtual/libc"
]

provides = [
    "m4"
]

[source]
url = "https://ftp.gnu.org/gnu/m4/m4-1.4.19.tar.xz"
sha256 = "63aede5c6d33b6d9b13511cd0be2cac046f2e70fd0a07aa9573a04a82783af96"

[build]
inherit = ["custom"]

dependencies = [
    "system/make"
]

[build.args]
compile_cmd = './configure --prefix=/usr CFLAGS="${CFLAGS} -std=gnu17 -Wno-error=int-conversion" && make -j${JOBS}'
install_cmd = './configure --prefix=/usr CFLAGS="${CFLAGS} -std=gnu17 -Wno-error=int-conversion" && make -j${JOBS} && make DESTDIR=${DESTDIR} install'

[build.payload]
default = "remaining"
