schema_version = 1

[package]
name = "texinfo"
version = "7.1.1"
release = 1
epoch = 0
description = "GNU documentation system"
license = "GPL-3.0-or-later"
channel = "system"
arch = "amd64"

dependencies = [
    "virtual/libc",
    "system/ncurses-libs >= 6.6-1"
]

[source]
url = "https://ftp.gnu.org/gnu/texinfo/texinfo-7.1.1.tar.xz"
sha256 = "31ae37e46283529432b61bee1ce01ed0090d599e606fc6a29dca1f77c76a6c82"

[build]
inherit = ["custom"]

dependencies = [
    "system/ncurses-dev >= 6.6-1"
]

[build.args]
compile_cmd = './configure --prefix=/usr CFLAGS="${CFLAGS} -std=gnu17" && make -j${JOBS}'
install_cmd = './configure --prefix=/usr CFLAGS="${CFLAGS} -std=gnu17" && make -j${JOBS} && make DESTDIR=${DESTDIR} install'

[build.payload]
default = "remaining"
