schema_version = 1

[package]
name = "dhcpcd"
version = "10.5.2"
release = 2
epoch = 0
description = "Basic RFC2131 compliant DHCP client daemon"
license = "BSD-2-Clause"
channel = "system"
arch = "amd64"

dependencies = [
    "virtual/libc"
]

provides = [
    "dhcpcd"
]

[source]
url = "https://github.com/NetworkConfiguration/dhcpcd/releases/download/v10.5.2/dhcpcd-10.5.2.tar.xz"
sha256 = "3e476657fdb6eeb38b277da3a48d0ac0113ecce5858ebdcddff2b629faed52b4"

[build]
inherit = ["custom"]

[build.args]
install_cmd = './configure --prefix=/usr --sysconfdir=/etc --rundir=/run --dbdir=/var/lib/dhcpcd --privsepuser=dhcpcd && make -j${JOBS} CFLAGS="${CFLAGS} -D_GNU_SOURCE" && make DESTDIR=${DESTDIR} install'

[build.payload]
default = "remaining"

[[sysusers]]
name = "dhcpcd"
type = "user"
description = "dhcpcd privilege separation user"
