schema_version = 1

[package]
name = "coreutils"
version = "9.6"
release = 1
epoch = 0
description = "GNU core system utilities (file, text, and shell utilities)"
license = "GPL-3.0-or-later"
channel = "system"
arch = "amd64"

dependencies = [
    "virtual/libc"
]

provides = [
    "virtual/coreutils"
]

[source]
url = "https://ftp.gnu.org/gnu/coreutils/coreutils-9.6.tar.xz"
sha256 = "7a0124327b398fd9eb1a6abde583389821422c744ffa10734b24f557610d3283"

[build]
inherit = ["autotools"]

[build.args]
configure_args = "--prefix=/usr --enable-install-program=hostname --enable-no-install-program=kill,uptime"

[build.payload]
default = "remaining"
