schema_version = 1

[package]
name = "cmake"
version = "3.31.5"
release = 1
epoch = 0
description = "Cross-platform open-source build system"
license = "BSD-3-Clause"
channel = "system"
arch = "amd64"

dependencies = [
    "virtual/libc",
    "system/gcc-libs:16",
    "system/zlib-libs >= 1.3.1-1",
    "system/zstd-libs >= 1.5.7-1"
]

[source]
url = "https://github.com/Kitware/CMake/releases/download/v3.31.5/cmake-3.31.5.tar.gz"
sha256 = "66fb53a145648be56b46fa9e8ccade3a4d0dfc92e401e52ce76bdad1fea43d27"

[build]
inherit = ["custom"]

dependencies = [
    "virtual/libc-dev",
    "system/make",
    "system/zlib-dev >= 1.3.1-1",
    "system/zstd-dev >= 1.5.7-1",
    "system/openssl-dev >= 3.4.1-1",
    "gcc16/gcc:16",
    "gcc16/gcc-dev:16"
]

[build.args]
install_cmd = '''sed -i 's#\#if (defined(__linux__) && !defined(__ANDROID__)) || defined(_WIN32)#\#if !defined(CMAKE_BOOTSTRAP) \&\& ((defined(__linux__) \&\& !defined(__ANDROID__)) || defined(_WIN32))#' Source/cmake.cxx && sed -i 's/USE_LIBIDN2 ON/USE_LIBIDN2 OFF/g' Utilities/cmcurl/CMakeLists.txt && sed -i 's/USE_NGHTTP2 ON/USE_NGHTTP2 OFF/g' Utilities/cmcurl/CMakeLists.txt && ./bootstrap --prefix=/usr --parallel=${JOBS} && make -j${JOBS} && make DESTDIR=${DESTDIR} install'''

[build.payload]
default = "remaining"
