schema_version = 1

[package]
name = "make"
version = "4.4.1"
release = 1
epoch = 0
description = "GNU version of the make utility"
license = "GPL-3.0-or-later"
channel = "system"
arch = "amd64"

dependencies = [
    "virtual/libc"
]

[source]
url = "https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz"
sha256 = "dd16fb1d67bfab79a72f5e8390735c49e3e8e70b4945a15ab1f81ddb78658fb3"

[build]
inherit = ["custom"]

[build.args]
install_cmd = './configure --prefix=/usr --without-guile && ./build.sh && ./make DESTDIR=${DESTDIR} install'

[build.payload]
default = "remaining"
