schema_version = 1

[package]
name = "kmod"
version = "34.2"
release = 1
epoch = 0
description = "Linux kernel module management tools and library"
license = "GPL-2.0-or-later AND LGPL-2.1-or-later"
channel = "system"
arch = "amd64"

dependencies = [
    "virtual/libc",
    "kmod-libs = 34.2-1"
]

provides = [
    "kmod"
]

[source]
url = "https://mirrors.edge.kernel.org/pub/linux/utils/kernel/kmod/kmod-34.2.tar.xz"
sha256 = "5a5d5073070cc7e0c7a7a3c6ec2a0e1780850c8b47b3e3892226b93ffcb9cb54"

[build]
inherit = ["autotools"]

[build.args]
configure_args = "--with-zstd --with-xz --with-zlib --disable-manpages"

[build.payload]
default = "remaining"

[[subpackages]]
name = "kmod-libs"
description = "Linux kernel module runtime shared library"
license = "LGPL-2.1-or-later"

dependencies = [
    "virtual/libc",
    "zstd-libs >= 1.5.7-1",
    "xz-libs >= 5.8.3-1",
    "zlib-libs >= 1.3.1-1"
]

provides = [
    "so:libkmod.so.2"
]

[subpackages.payload]
files = [
    "usr/lib/*.so.*"
]

[[subpackages]]
name = "kmod-dev"
description = "Linux kernel module development headers and link library"
license = "LGPL-2.1-or-later"

dependencies = [
    "kmod-libs = 34.2-1"
]

[subpackages.payload]
files = [
    "usr/include/**",
    "usr/lib/*.so",
    "usr/lib/pkgconfig/*.pc"
]
