schema_version = 1

[package]
name = "iproute2"
version = "7.2.0"
release = 1
epoch = 0
description = "IP routing and network configuration utilities"
license = "GPL-2.0-or-later"
channel = "system"
arch = "amd64"

dependencies = [
    "virtual/libc",
    "libcap-libs >= 2.78-1"
]

provides = [
    "iproute2"
]

[source]
url = "https://mirrors.edge.kernel.org/pub/linux/utils/net/iproute2/iproute2-7.2.0.tar.xz"
sha256 = "4c2fa124c2cf0afd7ca34d1eeacba6ba048a56f6374e2aab93dafbdbd4eea9c0"

[build]
inherit = ["custom"]

[build.args]
install_cmd = './configure --prefix=/usr && make -j${JOBS} && make DESTDIR=${DESTDIR} install'

[build.payload]
default = "remaining"

[[subpackages]]
name = "iproute2-dev"
description = "IP routing and network configuration development headers"
license = "GPL-2.0-or-later"

dependencies = [
    "iproute2 = 7.2.0-1"
]

[subpackages.payload]
files = [
    "usr/include/**"
]
