schema_version = 1
name = "init-loom"
description = "Loom Service Generator and Controller Class"

[service_generator]
target_path = "/usr/lib/loom/services/${service.name}.toml"
mode = 420
supported_types = ["simple", "notify", "oneshot"]
compile_command = [
    "/usr/lib/loom/loom",
    "compile-service",
    "--from-sage",
    "${INPUT}",
    "--output",
    "${OUTPUT}",
]
managed_directory = "/usr/lib/loom/services"

validate_command = "/usr/lib/loom/loom validate --root ${SYSROOT}"
enable_cmd = "/usr/bin/loomctl --root ${SYSROOT} enable ${service.name}"
disable_cmd = "/usr/bin/loomctl --root ${SYSROOT} disable ${service.name}"
is_enabled_cmd = "/usr/bin/loomctl --root ${SYSROOT} is-enabled ${service.name}"

template = """
schema_version = 2

[service]
name = "${service.name}"
description = ${service.description_json}
command = ${service.command_json}
${service.stop_input_toml}
${service.reload_input_toml}
user = ${service.user_json}
group = ${service.group_json}
type = "${service.process_type}"
readiness = "${service.readiness}"
working_directory = ${service.working_dir_json}
restart = "${service.restart}"
after = ${service.after_json}
before = ${service.before_json}
"""
