schema_version = 1

[package]
name = "grep"
version = "3.12"
release = 1
epoch = 0
description = "GNU grep, egrep and fgrep"
license = "GPL-3.0-or-later"
channel = "system"
arch = "amd64"

dependencies = [
    "virtual/libc"
]

provides = [
    "grep"
]

[source]
url = "https://ftp.gnu.org/gnu/grep/grep-3.12.tar.xz"
sha256 = "2649b27c0e90e632eadcd757be06c6e9a4f48d941de51e7c0f83ff76408a07b9"

[build]
inherit = ["autotools"]

[build.payload]
default = "remaining"
