schema_version = 1

[package]
name = "gperf"
version = "3.1"
release = 1
epoch = 0
description = "Perfect hash function generator"
license = "GPL-3.0-or-later"
channel = "system"
arch = "amd64"

dependencies = [
    "virtual/libc",
    "system/gcc-libs:16"
]

[source]
url = "https://mirrors.kernel.org/gnu/gperf/gperf-3.1.tar.gz"
sha256 = "588546b945bba4b70b6a3a616e80b4ab466e3f33024a352fc2198112cdbb3ae2"

[build]
inherit = ["custom"]

dependencies = [
    "virtual/libc-dev",
    "system/make",
    "gcc16/gcc:16",
    "gcc16/gcc-dev:16"
]

[build.args]
install_cmd = "./configure --prefix=/usr && make -j${JOBS} && make DESTDIR=${DESTDIR} install"

[build.payload]
default = "remaining"
