schema_version = 1

[package]
name = "flex"
version = "2.6.4"
release = 1
epoch = 0
description = "Fast lexical analyzer generator"
license = "BSD-2-Clause"
channel = "system"
arch = "amd64"

dependencies = [
    "virtual/libc",
    "m4"
]

[source]
url = "https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz"
sha256 = "e87aae032bf07c26f85ac0ed3250998c37621d95f8bd748b31f15b33c45ee995"

[build]
inherit = ["autotools"]

[build.payload]
default = "remaining"

[[subpackages]]
name = "flex-libs"
description = "Flex runtime shared library"
license = "BSD-2-Clause"

dependencies = [
    "virtual/libc"
]

provides = [
    "so:libfl.so.2"
]

[subpackages.payload]
files = [
    "usr/lib/*.so.*"
]

[[subpackages]]
name = "flex-dev"
description = "Flex development headers and link library"
license = "BSD-2-Clause"

dependencies = [
    "flex-libs = 2.6.4-1"
]

[subpackages.payload]
files = [
    "usr/include/**",
    "usr/lib/*.so"
]
